server:
  port: 1001
  context-path: /

# 数据源配置
spring:
  application:
      name: microservice-ticket #配置服务提供者名称，便于ribbon负载均衡根据名称调用
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_station
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
# eureka 注册中心配置
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-ticket  #客户端服务名
    instance-id: microservice-ticket:1001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      #defaultZone: http://localhost:2001/eureka #(单机eureka)把服务注册到eureka注册中心，要和前面服务注册中心（microservice-eureka-server-2001）的defaultZone暴露地址一致
      defaultZone: http://eureka2001.wfd360.com:2001/eureka/,http://eureka2002.wfd360.com:2002/eureka/,http://eureka2003.wfd360.com:2003/eureka/ # 集群

# 服务提供者联系信息
info:
   version: v2
   负责人: 姿势帝 - 博客园
   微  信: 851298348